### ISSUE TITLE
After config on macOS , cannot access network

### ISSUE THREAD

**Issue by leona0918** [kiron1/proxydetox#110]
## system info
proxydetox version 0.4.4
macOS BIG SUR  11.6
proxydetox config file:
- $HOME/Library/Application Support/proxydetox/proxy.pac
 > which is a copy of corporate proxy pac file
- $HOME/Library/Application Support/proxydetox/proxydetoxrc
 > only set --negotiate

set HTTP_PROXY HTTPS_PROXY to .zshrc file
change network setting 'Automatic Proxy Configuration' URL to 'http:127.0.0.1/proxy.pac'

## steps to reduce the issue
```zsh
proxydetox
```
> **error message**
 Authenticator factory: negotiate
thread 'main' panicked at 'error binding to 127.0.0.1:3128: error creating server listener: Address already in use (os error 48)', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.17/src/server/server.rs:87:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

If try to re start wifi , failed to connect to network.
Hope I described it clear.....

**Comment by leona0918** [comment]
The above error message is because previously I have configured to start proxydetox when a user session is active.
The latest status is :
**proxydetox is running, can accessing network, but when connect corporate vpn , cannot access network.**

not connect corporate VPN, stop proxydetox, can ping bing.com , but curl bing.com will got connection refused
![image](https://user-images.githubusercontent.com/32065490/161464988-ffa3bb3c-05da-481d-9c7a-4e0b7f924e5d.png)
not connect corporate VPN, start proxydetox , can ping bing.com , but curl bing.com get different error
![image](https://user-images.githubusercontent.com/32065490/161465411-94240d95-af81-4f56-a608-87db2ebfcb26.png)
connect corporate VPN, start proxydetox, cannot access network
![image](https://user-images.githubusercontent.com/32065490/161465819-e970491f-270d-41de-910d-3381a3ce7f55.png)
not connect corporate VPN, stop proxydetox, cannot access network
![image](https://user-images.githubusercontent.com/32065490/161466222-cfbbe5cc-1527-4962-b076-e32a989bb8b2.png)

**Comment by kiron1** [comment]
> thread 'main' panicked at 'error binding to 127.0.0.1:3128: error creating server listener: Address already in use

This indicates that some other process is listening already on localhost (127.0.0.1) on port 3128. Either it is a different proxy or application or proxydetox is already running.

Which means we have two problems here: 1) Something else is running on port 3128 already, 2) `--negotiate` is not working (Kerberos authentication against the proxy fails).


### Something else is running on port 3128 already

If you installed proxydetox via the provided packages, then it installs a `launchd` `plist` file at `/Library/LaunchAgents/com.github.kiron1.proxydetox.plist`.

You can check if proxydetox was started by `launchd` and is still running (check for `state = running`):

```
launchctl print gui/$(id -u)/com.github.kiron1.proxydetox
```

If this is not the case, you can use this command which other command is listening on `licalhost:3128`:

```sh
lsof -PiTCP -sTCP:LISTEN
```

If it was started by `launchd` you can **stop** it with:

```sh
launchctl kill SIGTERM gui/$(id -u)/com.github.kiron1.proxydetox
```

and **disable** it with (to prevent it from starting again):

```sh
launchctl disable gui/$(id -u)/com.github.kiron1.proxydetox
```

Now you should be able to just run `proxydetox` on the terminal and observe the log output.

### `--negotiate` is not working (Kerberos authentication against the proxy fails)

Given that you configured `--negotiate`, make sure that your systems Kerberos:

Use `klist` to see if the are any expired tickets and make sure there are entries for your proxys. If there are any issues, It might help to use `kinit` to login again.

### Enable proxydetox as service again

To undo the above steps of stopping and disabling proxydetox, we can **enable** it again with:

```sh
launchctl enable gui/$(id -u)/com.github.kiron1.proxydetox
```

and **start** it with:

```sh
launchctl kickstart -kp gui/$(id -u)/com.github.kiron1.proxydetox
```

**Comment by kiron1** [comment]
Here the answers for your second post:

### not connect corporate VPN, stop proxydetox

I think the problem here is, that `curl` is still trying to use the proxy which you switched off. Make sure you do not have the proxy variables still set (use `env` to list current variables), unsetting them with:

```sh
unset http_proxy https_proxy no_proxy HTTP_PROXY HTTPS_PROXY NO_PROXY
```

Also make sure there are not `--proxy` flags in `$HOME/.curlrc`

This advice applies also for other tools too: if not connected to the corporate network, make sure they are configured to not use any proxy.

### connect corporate VPN, start proxydetox, cannot access network

This looks correct, `curl -i bing.com` gives the reply from `bing.com`. Use `curl -iL bing.com` to follow the redirects and see the full page.

That `ping bing.com` is not working is expected, depending on your corporate network configuration they likely block all direct access to the outside of the network which does not go via the proxy(s).

**Comment by leona0918** [comment]
## some update
- I have enable proxydetox as service again, which proxydetox is running normally.
- The output of klist seems normal, nothing expired, but I still run kinit.
- below is output of `curl -iL bing.com`
  ### not connect corporate VPN, proxydetox running, can normally access network
![image](https://user-images.githubusercontent.com/32065490/161472813-701177e8-8894-4b23-809a-49ecb4966b4d.png)

  ###  connect corporate VPN, proxydetox running, cannot normally access network
  any clue? 🥲
 ![image](https://user-images.githubusercontent.com/32065490/161473115-bbba46e3-681e-452c-a050-d162c54f4a34.png)

**Comment by kiron1** [comment]
It looks like your screenshots do not match with the description?

### not connect corporate VPN, proxydetox running, can normally access network

Here proxydetox returns a 502 error, since you are not connected to the VPN it cannot establish a connection with the proxy -> this is the expected behaviour.

For this use case just disable the usage of any proxy and use direct connections, see https://github.com/kiron1/proxydetox/issues/110#issuecomment-1087068434

### connect corporate VPN, proxydetox running, cannot normally access network

In the screenshot everything looks correct. You write _cannot normally access network_ while the output shows that `curl` could create a connection to `bing.com` _via_ `proxydetox`.

**Comment by leona0918** [comment]
That's the funny part, I didn't mismatch the description and screenshots.
What I do care is this case ** connect corporate VPN, proxydetox running, cannot normally access network**
From the console output of `curl -iL bing.com`, it creates a connection, but chrome cannot see the result, and chrome does use computer's proxy setting. 🧐

**Comment by kiron1** [comment]
So `proxydetox` works as expected.

The problem seems that Chrome (and maybe Safari) is not piking up the right system configuration for the proxy.

I also noticed in the past, that Proxy settings in _System Preferences..._ where correct, but yet Safari and Chrome did not use the proxy and showed errors. When you run proxydetox in a Terminal you will see that proxydetox does not even registers and connection attempts from these browsers. On the other hand, Firefox allows to set custom proxy settings, configuring there to use `127.0.0.1:3128` worked.

This behaviour can be further analysed with:

```sh
scutil --proxy
```

```sh
networkservice=Wi-Fi
networksetup -getftpproxy "${networkservice}"
networksetup -getwebproxy "${networkservice}"
networksetup -getsecurewebproxy "${networkservice}"
networksetup -getstreamingproxy "${networkservice}"
networksetup -getgopherproxy "${networkservice}"
networksetup -getsocksfirewallproxy "${networkservice}"
networksetup -getproxybypassdomains "${networkservice}"
networksetup -getproxyautodiscovery "${networkservice}"
networksetup -getautoproxyurl "${networkservice}"
```

**Comment by leona0918** [comment]
`scutil --proxy`
  > <dictionary> {
  ProxyAutoConfigEnable : 1
  ProxyAutoConfigURLString : http://127.0.0.1/proxy.pac
}

`networksetup -getftpproxy "${networkservice}"`
`networksetup -getwebproxy "${networkservice}"`
`networksetup -getsecurewebproxy "${networkservice}"`
`networksetup -getstreamingproxy "${networkservice}"`
`networksetup -getgopherproxy "${networkservice}"`
`networksetup -getsocksfirewallproxy "${networkservice}"`

> Enabled: No
Server:
Port: 0
Authenticated Proxy Enabled: 0


`networksetup -getproxybypassdomains "${networkservice}"`
> There aren't any bypass domains set on Wi-Fi.

`networksetup -getproxyautodiscovery "${networkservice}"`
> Auto Proxy Discovery: Off

`networksetup -getautoproxyurl "${networkservice}"`
> URL: http://127.0.0.1/proxy.pac
Enabled: Yes

**Comment by kiron1** [comment]
Now I notice:

> change network setting 'Automatic Proxy Configuration' URL to 'http:127.0.0.1/proxy.pac'

The port is missing here, the URL should read: `http://127.0.0.1:3128/proxy.pac`

You can verify that `curl http://127.0.0.1:3128/proxy.pac` shows a PAC file (should be this fragment `function FindProxyForURL`): https://github.com/kiron1/proxydetox/blob/64482dab380c17898c9274baf62ce02483f12363/proxydetox/src/lib.rs#L11

**Comment by leona0918** [comment]
Actually I have tried to set the URL with port number , still not work in chrome.
But I install Firefox and set brower's proxy to `http://127.0.0.1:3128`, and how can  connect corporate vpn, run proxydetox, and access network.
I guess I can close this issue now. 
Thank you professor 😋🌈

**Comment by leona0918** [comment]
Or start Chrome with below command
`open -a "Google Chrome" --args --proxy-server=http://127.0.0.1:3128`

**Comment by kiron1** [comment]
I think the problem is, that you have an older version of proxydetox which does not yet offer the `http://localhost:3128/proxy.pac` endpoint.

The correct solution would be to configure **Web Proxy (HTTP)**, and **Secure Web Proxy (HTTPS)** with `127.0.0.1` and `3128`, see: https://support.apple.com/en-gb/guide/mac-help/mchlp2591/mac
