### ISSUE TITLE
variable missmatch

### ISSUE THREAD

**Issue by alex-anto21** [kiron1/proxydetox#374]
Hello,

I recently tried to install proxydetox deb package on a linux machine and I noticed that the proxydetox.service does not start due to the unit file.
![thumbnail_image001](https://github.com/kiron1/proxydetox/assets/74675991/4dd60ee7-5801-4d6c-8ea0-d013f7a3cbe8)
I compared the latest version with an old version and there can be a possible variable mismatch in pkg/deb/BUILD
![thumbnail_image002](https://github.com/kiron1/proxydetox/assets/74675991/6466b4c2-7bde-4371-b8af-61b68b74d3eb)

Thank you!

**Comment by kiron1** [comment]
Thanks for bringing this to our attention. I assume this issue was introduced in https://github.com/kiron1/proxydetox/commit/4f758efa47b23901c350743a04d346b1dab5af08.
In `main` it is already fixed. We need to wait for a new release, but there are currently some issues with the Bazel build and buildgen.
