### ISSUE TITLE
Using as a library from another rust app

### ISSUE THREAD

**Issue by amircodota** [kiron1/proxydetox#375]
I am writing a rust desktop app.

It uses [reqwest](https://github.com/seanmonstar/reqwest) (which internally uses hyper AFAIK) to make http requests.

I was wondering if it is possible to use proxydetox as a library instead of having to run it as an external process.

I tried to follow the code a bit, but it was complex for a networking noob like me :-)

If it is possible and you can provide some instructions, that would be great

**Comment by kiron1** [comment]
Interesting idea. Proxydetox is implemented by composing different libraries, at the same time Proxydetox does not provide a single library to handle all its functionality to be reused in other applications.

Right now reqwest is able to use a proxy for requests and therefore can use Proxydetox when installed.

Providing a library to be used with reqwest would be difficult since reqwest does not offer a method to implement any plugins or extensions.
